// Code generated by goctl. DO NOT EDIT.
package types

type AuthenticateResponse struct {
	Message string `json:"message"`
}

type LoginRequest struct {
	Mobile   string `json:"mobile"`   // 手机号
	Password string `json:"password"` // 密码
}

type LoginResponse struct {
	Token   Token  `json:"token"`
	Message string `json:"message"`
}

type LogoutResponse struct {
	Message string `json:"message"`
}

type RegisterRequest struct {
	Nickname         string `json:"nickname"`          // 用户名
	Mobile           string `json:"mobile"`            // 手机号
	Password         string `json:"password"`          // 密码
	VerificationCode string `json:"verification_code"` // 验证码
}

type RegisterResponse struct {
	UserID  int64  `json:"user_id"` // 用户ID
	Message string `json:"message"` // 注册成功响应消息
}

type Token struct {
	AccessToken  string `json:"access_token"`  // 访问令牌
	AccessExpire int64  `json:"access_expire"` // 访问令牌过期时间
}

type UserInfoResponse struct {
	UserID     int64  `json:"user_id"`
	Nickname   string `json:"nickname"`
	Mobile     string `json:"mobile"`
	Avatar     string `json:"avatar"`
	Role       int32  `json:"role"`
	Gender     int    `json:"gender"`
	Addr       string `json:"addr"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
	DeletedAt  string `json:"deleted_at"`
	Is_Deleted bool   `json:"is_deleted"`
	Message    string `json:"message"`
}

type VerificationRequest struct {
	Mobile string `json:"mobile"` // 手机号
}

type VerificationResponse struct {
	Message string `json:"message"` // 验证结果
}
