// Code generated by goctl. DO NOT EDIT.
package types

type AuthenticateRequest struct {
	Token     string `header:"Token,optional"`
	ValidPath string `header:"ValidPath,optional"`
}

type AuthenticateResponse struct {
	Message string `json:"message"`
}

type JWT struct {
	AccessToken  string `json:"access_token"`  // 访问令牌
	RefreshToken string `json:"refresh_token"` // 刷新令牌
}

type LoginRequest struct {
	Mobile   string `json:"mobile"`   // 手机号
	Password string `json:"password"` // 密码
}

type LoginResponse struct {
	JWT     JWT    `json:"jwt"`
	Message string `json:"message"`
}

type LogoutResponse struct {
	Message string `json:"message"`
}

type RegisterRequest struct {
	Nickname         string `json:"nickname"`          // 用户名
	Mobile           string `json:"mobile"`            // 手机号
	Password         string `json:"password"`          // 密码
	VerificationCode string `json:"verification_code"` // 验证码
}

type RegisterResponse struct {
	UserID  int64  `json:"user_id"` // 用户ID
	Message string `json:"message"` // 注册成功响应消息
}

type TestRequest struct {
	Test string `json:"test,optional"`
}

type TestResponse struct {
	StatusCode int32  `json:"status_code"`         // 状态码，0-成功，其他值-失败
	StatusMsg  string `json:"status_msg,optional"` // 返回状态描述
	Message    string `json:"message"`
}

type VerificationRequest struct {
	Mobile string `json:"mobile"` // 手机号
}

type VerificationResponse struct {
	Message string `json:"message"` // 验证结果
}
