// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	UserName string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token Token `json:"token"`
}

type ThirdPartyLoginInfoByQQReponse struct {
	Name string `json:"name"`
	Icon string `json:"icon"`
	Href string `json:"href"`
}

type Token struct {
	AccessToken  string `json:"access_token"`  // 访问令牌
	AccessExpire int64  `json:"access_expire"` // 访问令牌过期时间
}

type UserInfoResponse struct {
	UserID   uint   `json:"user_id"`
	UserName string `json:"user_name"`
	Message  string `json:"message"`
}
