// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"akita/panda-im/service/auth/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/authenticate",
				Handler: authenticateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getInfoByQQ",
				Handler: ThirdPartyLoignInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: loginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/logout",
				Handler: logoutHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/qqLogin",
				Handler: thirdPartyLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/api/auth"),
	)
}
