// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"akita/panda-im/service/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/userInfo",
				Handler: UserInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/api/user"),
	)
}
