// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoResponse struct {
	UserID   int64  `json:"user_id"`
	Nickname string `json:"nickname"`
	Mobile   string `json:"mobile"`
	Avatar   string `json:"avatar"`
	Role     int32  `json:"role"`
	Gender   int    `json:"gender"`
	Addr     string `json:"addr"`
	Abstract string `json:"abstract"`
	Message  string `json:"message"`
}

type UserInfonRequest struct {
	UserID int64  `json:"user_id"`
	Role   int32  `json:"role"`
	Mobile string `json:"mobile,optional"`
}
